import { supabase } from "@/integrations/supabase/client";
import { createOrUpdateClient } from "@/lib/client-portal.functions";
export type ClientType="particulier"|"residence"|"professionnel"; export type ReportPolicy="oui"|"non"|"a_confirmer"; export type ClientLifecycle="actif"|"perdu";
export const CLIENT_TYPE_META={particulier:{label:"Particulier",hint:"Client individuel / foyer."},residence:{label:"Résidence",hint:"Résidence ou ensemble immobilier."},professionnel:{label:"Professionnel",hint:"Entreprise ou organisme."}} as const;
export const LIFECYCLE_META={actif:{label:"Client suivi",hint:"Le client reste suivi.",badge:"border-emerald-200 bg-emerald-50 text-emerald-700"},perdu:{label:"Client perdu",hint:"Historique conservé, exclu des relances.",badge:"border-rose-200 bg-rose-50 text-rose-700"}} as const;
export const REPORT_POLICY_META={oui:{label:"Oui — client suivi par compte-rendu",short:"CR : oui",hint:"Les interventions terminées génèrent une action compte-rendu.",badge:"border-emerald-200 bg-emerald-50 text-emerald-700"},non:{label:"Non — client non concerné",short:"CR : non",hint:"Aucune alerte ni action compte-rendu.",badge:"border-border bg-muted text-muted-foreground"},a_confirmer:{label:"À confirmer",short:"CR à qualifier",hint:"À qualifier — jamais compté comme retard.",badge:"border-orange-200 bg-orange-50 text-orange-700"}} as const;
export interface Client{id:string;name:string;client_type:ClientType|null;civility:string|null;address:string|null;phone:string|null;email:string|null;emails:string[];contract_type:string|null;frequency:string|null;notes:string|null;cr_notes:string|null;ceev_enabled:boolean;ceev_planning_path:string|null;ceev_planning_filename:string|null;ceev_planning_updated_at:string|null;report_policy:ReportPolicy;lifecycle_status:ClientLifecycle;lost_at:string|null;source:string|null;source_confidence:string|null;created_at:string;updated_at:string;share_token:string;}
export type ClientInput={name:string;client_type?:ClientType|null;civility?:string|null;address?:string|null;phone?:string|null;email?:string|null;emails?:string[];contract_type?:string|null;frequency?:string|null;notes?:string|null;cr_notes?:string|null;ceev_enabled?:boolean;report_policy?:ReportPolicy;lifecycle_status?:ClientLifecycle;lost_at?:string|null;source?:string|null;source_confidence?:string|null};
export const CLIENT_SOURCE_CA="ca_historique"; export const CLIENT_SOURCE_LABEL:{[key:string]:string}={[CLIENT_SOURCE_CA]:"Création automatique depuis historique CA"};
export function clientEmails(c:{email?:string|null;emails?:string[]|null}){return Array.from(new Set([...(c.emails??[]),...(c.email?[c.email]:[])].map(e=>e.trim()).filter(Boolean)))}
export function gardenLabel(c:{name?:string|null}){return c.name?.trim()||"Jardin"}
function normalise(i:ClientInput){const p:Record<string,unknown>={};for(const[k,v]of Object.entries(i))if(v!==undefined)p[k]=v;if(Array.isArray(p.emails)){const list=Array.from(new Set((p.emails as unknown[]).map(e=>String(e).trim()).filter(Boolean)));p.emails=list;p.email=list[0]??null}if(typeof p.name==="string")p.name=p.name.trim();return p}
export async function listClients():Promise<Client[]>{const{data,error}=await supabase.from("clients").select("*").is("merged_into_client_id",null).order("name");if(error)throw new Error(`Impossible de charger les clients : ${error.message}`);return data as unknown as Client[]}
export async function getClient(id:string):Promise<Client>{const{data,error}=await supabase.from("clients").select("*").eq("id",id).single();if(error)throw new Error(`Impossible de charger la fiche client : ${error.message}`);return data as unknown as Client}
export async function createClient(i:ClientInput):Promise<Client>{const{data:auth}=await supabase.auth.getUser();if(!auth.user)throw new Error("Non authentifié");const payload=normalise(i);const data=await createOrUpdateClient({data:{mode:"create",userId:auth.user.id,payload}});return data as unknown as Client}
export async function updateClient(id:string,i:ClientInput):Promise<Client>{const data=await createOrUpdateClient({data:{mode:"update",id,payload:normalise(i)}});return data as unknown as Client}
export async function deleteClient(id:string):Promise<void>{const{error}=await supabase.from("clients").delete().eq("id",id);if(error)throw new Error(`Impossible de supprimer le client : ${error.message}`)}
