import { useEffect, useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ComposedChart, Legend, Line, LineChart, Pie, PieChart, PolarAngleAxis, PolarGrid, Radar, RadarChart, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, ZAxis } from "recharts";
import { BarChart3 } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { formatEuro } from "@/lib/pilot";
import { contractHourlyMarginRate, type CeevContract } from "@/lib/ceev";

type ChartType = "barres" | "barres_h" | "groupees" | "empilees" | "courbe" | "aire" | "combo" | "donut" | "radar" | "nuage";
type Dimension = "client" | "contrat" | "annee";
type Metric = "ca" | "charges" | "marge" | "heures" | "taux";
const CHARTS=[{value:"barres",label:"Barres verticales"},{value:"barres_h",label:"Barres horizontales"},{value:"groupees",label:"Barres groupées"},{value:"empilees",label:"Barres empilées"},{value:"courbe",label:"Courbe"},{value:"aire",label:"Aire"},{value:"combo",label:"Barres + courbe"},{value:"donut",label:"Donut"},{value:"radar",label:"Radar"},{value:"nuage",label:"Nuage de points"}] as const;
const METRICS=[{value:"ca",label:"CA HT",unit:"€ HT"},{value:"charges",label:"Charges",unit:"€ HT"},{value:"marge",label:"Marge nette",unit:"€ HT"},{value:"heures",label:"Heures",unit:"h"},{value:"taux",label:"Taux horaire de marge",unit:"€/h"}] as const;
const metricMeta=(m:Metric)=>METRICS.find(x=>x.value===m)??METRICS[0];
function value(c:CeevContract,m:Metric){switch(m){case"ca":return c.pv_ht??0;case"charges":return c.charges??0;case"marge":return(c.pv_ht??0)-(c.charges??0);case"heures":return c.hours??0;case"taux":return contractHourlyMarginRate(c)??0;}}
function fmt(m:Metric,n:number){if(m==="heures")return `${n.toLocaleString("fr-FR",{maximumFractionDigits:1})} h`;if(m==="taux")return `${formatEuro(n)}/h`;return formatEuro(n);}
function tick(m:Metric,n:number){if(m==="heures")return `${n.toLocaleString("fr-FR",{maximumFractionDigits:0})} h`;if(m==="taux")return `${Math.round(n).toLocaleString("fr-FR")} €/h`;return `${Math.round(n).toLocaleString("fr-FR")} €`;}
function usePersist(key:string,fallback:string,allowed:readonly string[]){const[v,setV]=useState(fallback);useEffect(()=>{try{const x=localStorage.getItem(key);if(x&&allowed.includes(x))setV(x)}catch{}},[key]);const set=(x:string)=>{if(!allowed.includes(x))return;setV(x);try{localStorage.setItem(key,x)}catch{}};return[v,set] as const;}
interface Props{year:number;contracts:CeevContract[];revenueSeries:Array<{year:number;ca:number;margin:number}>;breakdown:Array<{clientId:string|null;clientName:string;count:number;ca:number}>;}
export function CeevFlexibleChart({year,contracts,breakdown}:Props){
 const[chart,setChart]=usePersist("pp:ceev:chart","barres",CHARTS.map(x=>x.value));const[dimension,setDimension]=usePersist("pp:ceev:dimension","client",["client","contrat","annee"]);const[primary,setPrimary]=usePersist("pp:ceev:primary","ca",METRICS.map(x=>x.value));const[secondary,setSecondary]=usePersist("pp:ceev:secondary","marge",METRICS.map(x=>x.value));const p=primary as Metric,s=secondary as Metric;
 const rows=useMemo(()=>{if(dimension==="client")return breakdown.map(b=>{const cs=contracts.filter(c=>(c.client_name??"Non rattaché")===b.clientName);return{name:b.clientName,primary:cs.reduce((a,c)=>a+value(c,p),0),secondary:cs.reduce((a,c)=>a+value(c,s),0)}});if(dimension==="contrat")return contracts.slice(0,20).map(c=>({name:c.client_name??c.raw_label,primary:value(c,p),secondary:value(c,s)}));return contracts.reduce((a,c)=>{const k=String(c.year??year);let r=a.find(x=>x.name===k);if(!r){r={name:k,primary:0,secondary:0};a.push(r)}r.primary+=value(c,p);r.secondary+=value(c,s);return a},[] as Array<{name:string;primary:number;secondary:number}>).sort((a,b)=>Number(a.name)-Number(b.name));},[contracts,breakdown,dimension,p,s,year]);
 const pn=metricMeta(p).label,sn=metricMeta(s).label,pu=metricMeta(p).unit,su=metricMeta(s).unit,xLabel=dimension==="client"?"Client":dimension==="contrat"?"Contrat":"Année";
 const tip=(v:number|string,n:string)=>[fmt(n===sn?s:p,Number(v)),n];
 const axes=<><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:11}} interval={0} label={{value:xLabel,position:"insideBottom",offset:-8,fontSize:11}}/><YAxis tick={{fontSize:11}} width={88} tickFormatter={v=>tick(p,Number(v))} label={{value:pu,angle:-90,position:"insideLeft",offset:8,fontSize:11}}/><Tooltip formatter={tip}/><Legend wrapperStyle={{fontSize:11}}/></>;
 const render=()=>{if(!rows.length)return <div className="flex h-[260px] items-center justify-center text-sm text-muted-foreground"><BarChart3 className="mr-2 h-5 w-5"/>Aucune donnée à représenter.</div>;switch(chart as ChartType){
 case"barres":return <BarChart data={rows}>{axes}<Bar dataKey="primary" name={`${pn} (${pu})`} fill="var(--pp-sales)"/></BarChart>;
 case"barres_h":return <BarChart data={rows} layout="vertical" margin={{left:20,right:20,bottom:20}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" tick={{fontSize:11}} tickFormatter={v=>tick(p,Number(v))} label={{value:pu,position:"insideBottom",offset:-12,fontSize:11}}/><YAxis type="category" dataKey="name" width={120} tick={{fontSize:11}} label={{value:xLabel,angle:-90,position:"insideLeft",fontSize:11}}/><Tooltip formatter={tip}/><Legend/><Bar dataKey="primary" name={`${pn} (${pu})`} fill="var(--pp-sales)"/></BarChart>;
 case"groupees":return <BarChart data={rows}>{axes}<Bar dataKey="primary" name={`${pn} (${pu})`} fill="var(--pp-sales)"/><Bar dataKey="secondary" name={`${sn} (${su})`} fill="var(--pp-mid)"/></BarChart>;
 case"empilees":return <BarChart data={rows}>{axes}<Bar dataKey="primary" name={`${pn} (${pu})`} stackId="a" fill="var(--pp-sales)"/><Bar dataKey="secondary" name={`${sn} (${su})`} stackId="a" fill="var(--pp-mid)"/></BarChart>;
 case"courbe":return <LineChart data={rows}>{axes}<Line type="monotone" dataKey="primary" name={`${pn} (${pu})`} stroke="var(--pp-sales)" strokeWidth={2} dot={{r:3}}/></LineChart>;
 case"aire":return <AreaChart data={rows}>{axes}<Area type="monotone" dataKey="primary" name={`${pn} (${pu})`} stroke="var(--pp-sales)" fill="var(--pp-sales)" fillOpacity={.18}/></AreaChart>;
 case"combo":return <ComposedChart data={rows}>{axes}<Bar dataKey="primary" name={`${pn} (${pu})`} fill="var(--pp-sales)"/><Line type="monotone" dataKey="secondary" name={`${sn} (${su})`} stroke="var(--pp-mid)" strokeWidth={2}/></ComposedChart>;
 case"donut":{const d=rows.map(r=>({name:r.name,value:Math.max(0,r.primary)})).filter(x=>x.value>0);return <PieChart><Pie data={d} dataKey="value" nameKey="name" innerRadius="52%" outerRadius="78%" paddingAngle={2}>{d.map((_,i)=><Cell key={i} fill={i%2?"var(--pp-mid)":"var(--pp-sales)"}/>)}</Pie><Tooltip formatter={(v:number)=>fmt(p,v)}/><Legend/></PieChart>}
 case"radar":return <RadarChart data={rows.slice(0,8)}><PolarGrid/><PolarAngleAxis dataKey="name" tick={{fontSize:10}}/><Radar name={`${pn} (${pu})`} dataKey="primary" stroke="var(--pp-sales)" fill="var(--pp-sales)" fillOpacity={.22}/><Tooltip formatter={(v:number)=>fmt(p,v)}/></RadarChart>;
 case"nuage":return <ScatterChart margin={{top:12,right:20,bottom:28,left:12}}><CartesianGrid/><XAxis type="number" dataKey="primary" name={pn} tick={{fontSize:11}} tickFormatter={v=>tick(p,Number(v))} label={{value:`${pn} (${pu})`,position:"insideBottom",offset:-18,fontSize:11}}/><YAxis type="number" dataKey="secondary" name={sn} tick={{fontSize:11}} tickFormatter={v=>tick(s,Number(v))} label={{value:`${sn} (${su})`,angle:-90,position:"insideLeft",fontSize:11}}/><ZAxis range={[40,180]}/><Tooltip cursor={{strokeDasharray:"3 3"}} formatter={(v:number,n:string)=>[fmt(n===sn?s:p,v),n]}/><Legend/><Scatter name={`${pn} / ${sn}`} data={rows} fill="var(--pp-sales)"/></ScatterChart>;}}
 return <Card><CardHeader className="pb-2"><div className="flex flex-wrap items-center justify-between gap-2"><div><CardTitle className="text-base">Analyse graphique CEEV</CardTitle><p className="text-xs text-muted-foreground">{year} · Unités et axes adaptés à la sélection.</p></div><div className="flex flex-wrap gap-2"><Select value={chart} onValueChange={setChart}><SelectTrigger className="h-8 w-44 text-xs"><SelectValue/></SelectTrigger><SelectContent>{CHARTS.map(c=><SelectItem key={c.value} value={c.value} className="text-xs">{c.label}</SelectItem>)}</SelectContent></Select><Select value={dimension} onValueChange={setDimension}><SelectTrigger className="h-8 w-32 text-xs"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="client">Par client</SelectItem><SelectItem value="contrat">Par contrat</SelectItem><SelectItem value="annee">Par année</SelectItem></SelectContent></Select><Select value={primary} onValueChange={setPrimary}><SelectTrigger className="h-8 w-36 text-xs"><SelectValue/></SelectTrigger><SelectContent>{METRICS.map(m=><SelectItem key={m.value} value={m.value} className="text-xs">{m.label}</SelectItem>)}</SelectContent></Select><Select value={secondary} onValueChange={setSecondary}><SelectTrigger className="h-8 w-36 text-xs"><SelectValue/></SelectTrigger><SelectContent>{METRICS.map(m=><SelectItem key={m.value} value={m.value} className="text-xs">2e · {m.label}</SelectItem>)}</SelectContent></Select></div></div></CardHeader><CardContent><div className="h-[320px] w-full"><ResponsiveContainer width="100%" height="100%">{render()}</ResponsiveContainer></div></CardContent></Card>;
}