/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as PartageTokenRouteImport } from './routes/partage.$token'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedVersionsRouteImport } from './routes/_authenticated/versions'
import { Route as AuthenticatedStatistiquesRouteImport } from './routes/_authenticated/statistiques'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPlanningRouteImport } from './routes/_authenticated/planning'
import { Route as AuthenticatedPilotRouteImport } from './routes/_authenticated/pilot'
import { Route as AuthenticatedPersonnalisationRouteImport } from './routes/_authenticated/personnalisation'
import { Route as AuthenticatedModelesRouteImport } from './routes/_authenticated/modeles'
import { Route as AuthenticatedEmailsRouteImport } from './routes/_authenticated/emails'
import { Route as AuthenticatedBackendRouteImport } from './routes/_authenticated/backend'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPilotIndexRouteImport } from './routes/_authenticated/pilot.index'
import { Route as AuthenticatedInterventionsIndexRouteImport } from './routes/_authenticated/interventions.index'
import { Route as AuthenticatedFichesIndexRouteImport } from './routes/_authenticated/fiches.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicEmailOpenRouteImport } from './routes/api/public/email-open'
import { Route as AuthenticatedPilotObjectifsRouteImport } from './routes/_authenticated/pilot.objectifs'
import { Route as AuthenticatedPilotFinanceRouteImport } from './routes/_authenticated/pilot.finance'
import { Route as AuthenticatedPilotClientsRouteImport } from './routes/_authenticated/pilot.clients'
import { Route as AuthenticatedPilotCaRouteImport } from './routes/_authenticated/pilot.ca'
import { Route as AuthenticatedInterventionsNewRouteImport } from './routes/_authenticated/interventions.new'
import { Route as AuthenticatedInterventionsInterventionIdRouteImport } from './routes/_authenticated/interventions.$interventionId'
import { Route as AuthenticatedFichesNewRouteImport } from './routes/_authenticated/fiches.new'
import { Route as AuthenticatedFichesFicheIdRouteImport } from './routes/_authenticated/fiches.$ficheId'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients.$clientId'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PartageTokenRoute = PartageTokenRouteImport.update({
  id: '/partage/$token',
  path: '/partage/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVersionsRoute = AuthenticatedVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatistiquesRoute =
  AuthenticatedStatistiquesRouteImport.update({
    id: '/statistiques',
    path: '/statistiques',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanningRoute = AuthenticatedPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPilotRoute = AuthenticatedPilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonnalisationRoute =
  AuthenticatedPersonnalisationRouteImport.update({
    id: '/personnalisation',
    path: '/personnalisation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelesRoute = AuthenticatedModelesRouteImport.update({
  id: '/modeles',
  path: '/modeles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailsRoute = AuthenticatedEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackendRoute = AuthenticatedBackendRouteImport.update({
  id: '/backend',
  path: '/backend',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPilotIndexRoute = AuthenticatedPilotIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPilotRoute,
} as any)
const AuthenticatedInterventionsIndexRoute =
  AuthenticatedInterventionsIndexRouteImport.update({
    id: '/interventions/',
    path: '/interventions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFichesIndexRoute =
  AuthenticatedFichesIndexRouteImport.update({
    id: '/fiches/',
    path: '/fiches/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailOpenRoute = ApiPublicEmailOpenRouteImport.update({
  id: '/api/public/email-open',
  path: '/api/public/email-open',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPilotObjectifsRoute =
  AuthenticatedPilotObjectifsRouteImport.update({
    id: '/objectifs',
    path: '/objectifs',
    getParentRoute: () => AuthenticatedPilotRoute,
  } as any)
const AuthenticatedPilotFinanceRoute =
  AuthenticatedPilotFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedPilotRoute,
  } as any)
const AuthenticatedPilotClientsRoute =
  AuthenticatedPilotClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedPilotRoute,
  } as any)
const AuthenticatedPilotCaRoute = AuthenticatedPilotCaRouteImport.update({
  id: '/ca',
  path: '/ca',
  getParentRoute: () => AuthenticatedPilotRoute,
} as any)
const AuthenticatedInterventionsNewRoute =
  AuthenticatedInterventionsNewRouteImport.update({
    id: '/interventions/new',
    path: '/interventions/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterventionsInterventionIdRoute =
  AuthenticatedInterventionsInterventionIdRouteImport.update({
    id: '/interventions/$interventionId',
    path: '/interventions/$interventionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFichesNewRoute = AuthenticatedFichesNewRouteImport.update({
  id: '/fiches/new',
  path: '/fiches/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFichesFicheIdRoute =
  AuthenticatedFichesFicheIdRouteImport.update({
    id: '/fiches/$ficheId',
    path: '/fiches/$ficheId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/pending': typeof PendingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/backend': typeof AuthenticatedBackendRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/modeles': typeof AuthenticatedModelesRoute
  '/personnalisation': typeof AuthenticatedPersonnalisationRoute
  '/pilot': typeof AuthenticatedPilotRouteWithChildren
  '/planning': typeof AuthenticatedPlanningRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statistiques': typeof AuthenticatedStatistiquesRoute
  '/versions': typeof AuthenticatedVersionsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/partage/$token': typeof PartageTokenRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/fiches/$ficheId': typeof AuthenticatedFichesFicheIdRoute
  '/fiches/new': typeof AuthenticatedFichesNewRoute
  '/interventions/$interventionId': typeof AuthenticatedInterventionsInterventionIdRoute
  '/interventions/new': typeof AuthenticatedInterventionsNewRoute
  '/pilot/ca': typeof AuthenticatedPilotCaRoute
  '/pilot/clients': typeof AuthenticatedPilotClientsRoute
  '/pilot/finance': typeof AuthenticatedPilotFinanceRoute
  '/pilot/objectifs': typeof AuthenticatedPilotObjectifsRoute
  '/api/public/email-open': typeof ApiPublicEmailOpenRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/fiches/': typeof AuthenticatedFichesIndexRoute
  '/interventions/': typeof AuthenticatedInterventionsIndexRoute
  '/pilot/': typeof AuthenticatedPilotIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/pending': typeof PendingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/backend': typeof AuthenticatedBackendRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/modeles': typeof AuthenticatedModelesRoute
  '/personnalisation': typeof AuthenticatedPersonnalisationRoute
  '/planning': typeof AuthenticatedPlanningRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statistiques': typeof AuthenticatedStatistiquesRoute
  '/versions': typeof AuthenticatedVersionsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/partage/$token': typeof PartageTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/fiches/$ficheId': typeof AuthenticatedFichesFicheIdRoute
  '/fiches/new': typeof AuthenticatedFichesNewRoute
  '/interventions/$interventionId': typeof AuthenticatedInterventionsInterventionIdRoute
  '/interventions/new': typeof AuthenticatedInterventionsNewRoute
  '/pilot/ca': typeof AuthenticatedPilotCaRoute
  '/pilot/clients': typeof AuthenticatedPilotClientsRoute
  '/pilot/finance': typeof AuthenticatedPilotFinanceRoute
  '/pilot/objectifs': typeof AuthenticatedPilotObjectifsRoute
  '/api/public/email-open': typeof ApiPublicEmailOpenRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/fiches': typeof AuthenticatedFichesIndexRoute
  '/interventions': typeof AuthenticatedInterventionsIndexRoute
  '/pilot': typeof AuthenticatedPilotIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/pending': typeof PendingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/backend': typeof AuthenticatedBackendRoute
  '/_authenticated/emails': typeof AuthenticatedEmailsRoute
  '/_authenticated/modeles': typeof AuthenticatedModelesRoute
  '/_authenticated/personnalisation': typeof AuthenticatedPersonnalisationRoute
  '/_authenticated/pilot': typeof AuthenticatedPilotRouteWithChildren
  '/_authenticated/planning': typeof AuthenticatedPlanningRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/statistiques': typeof AuthenticatedStatistiquesRoute
  '/_authenticated/versions': typeof AuthenticatedVersionsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/partage/$token': typeof PartageTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/fiches/$ficheId': typeof AuthenticatedFichesFicheIdRoute
  '/_authenticated/fiches/new': typeof AuthenticatedFichesNewRoute
  '/_authenticated/interventions/$interventionId': typeof AuthenticatedInterventionsInterventionIdRoute
  '/_authenticated/interventions/new': typeof AuthenticatedInterventionsNewRoute
  '/_authenticated/pilot/ca': typeof AuthenticatedPilotCaRoute
  '/_authenticated/pilot/clients': typeof AuthenticatedPilotClientsRoute
  '/_authenticated/pilot/finance': typeof AuthenticatedPilotFinanceRoute
  '/_authenticated/pilot/objectifs': typeof AuthenticatedPilotObjectifsRoute
  '/api/public/email-open': typeof ApiPublicEmailOpenRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/fiches/': typeof AuthenticatedFichesIndexRoute
  '/_authenticated/interventions/': typeof AuthenticatedInterventionsIndexRoute
  '/_authenticated/pilot/': typeof AuthenticatedPilotIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/confidentialite'
    | '/pending'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/admin'
    | '/backend'
    | '/emails'
    | '/modeles'
    | '/personnalisation'
    | '/pilot'
    | '/planning'
    | '/settings'
    | '/statistiques'
    | '/versions'
    | '/email/unsubscribe'
    | '/partage/$token'
    | '/clients/$clientId'
    | '/fiches/$ficheId'
    | '/fiches/new'
    | '/interventions/$interventionId'
    | '/interventions/new'
    | '/pilot/ca'
    | '/pilot/clients'
    | '/pilot/finance'
    | '/pilot/objectifs'
    | '/api/public/email-open'
    | '/lovable/email/suppression'
    | '/clients/'
    | '/fiches/'
    | '/interventions/'
    | '/pilot/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/confidentialite'
    | '/pending'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/admin'
    | '/backend'
    | '/emails'
    | '/modeles'
    | '/personnalisation'
    | '/planning'
    | '/settings'
    | '/statistiques'
    | '/versions'
    | '/email/unsubscribe'
    | '/partage/$token'
    | '/'
    | '/clients/$clientId'
    | '/fiches/$ficheId'
    | '/fiches/new'
    | '/interventions/$interventionId'
    | '/interventions/new'
    | '/pilot/ca'
    | '/pilot/clients'
    | '/pilot/finance'
    | '/pilot/objectifs'
    | '/api/public/email-open'
    | '/lovable/email/suppression'
    | '/clients'
    | '/fiches'
    | '/interventions'
    | '/pilot'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/confidentialite'
    | '/pending'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/_authenticated/admin'
    | '/_authenticated/backend'
    | '/_authenticated/emails'
    | '/_authenticated/modeles'
    | '/_authenticated/personnalisation'
    | '/_authenticated/pilot'
    | '/_authenticated/planning'
    | '/_authenticated/settings'
    | '/_authenticated/statistiques'
    | '/_authenticated/versions'
    | '/email/unsubscribe'
    | '/partage/$token'
    | '/_authenticated/'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/fiches/$ficheId'
    | '/_authenticated/fiches/new'
    | '/_authenticated/interventions/$interventionId'
    | '/_authenticated/interventions/new'
    | '/_authenticated/pilot/ca'
    | '/_authenticated/pilot/clients'
    | '/_authenticated/pilot/finance'
    | '/_authenticated/pilot/objectifs'
    | '/api/public/email-open'
    | '/lovable/email/suppression'
    | '/_authenticated/clients/'
    | '/_authenticated/fiches/'
    | '/_authenticated/interventions/'
    | '/_authenticated/pilot/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  PendingRoute: typeof PendingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  PartageTokenRoute: typeof PartageTokenRoute
  ApiPublicEmailOpenRoute: typeof ApiPublicEmailOpenRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/partage/$token': {
      id: '/partage/$token'
      path: '/partage/$token'
      fullPath: '/partage/$token'
      preLoaderRoute: typeof PartageTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/versions': {
      id: '/_authenticated/versions'
      path: '/versions'
      fullPath: '/versions'
      preLoaderRoute: typeof AuthenticatedVersionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistiques': {
      id: '/_authenticated/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof AuthenticatedStatistiquesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planning': {
      id: '/_authenticated/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof AuthenticatedPlanningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pilot': {
      id: '/_authenticated/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof AuthenticatedPilotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personnalisation': {
      id: '/_authenticated/personnalisation'
      path: '/personnalisation'
      fullPath: '/personnalisation'
      preLoaderRoute: typeof AuthenticatedPersonnalisationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modeles': {
      id: '/_authenticated/modeles'
      path: '/modeles'
      fullPath: '/modeles'
      preLoaderRoute: typeof AuthenticatedModelesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emails': {
      id: '/_authenticated/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof AuthenticatedEmailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backend': {
      id: '/_authenticated/backend'
      path: '/backend'
      fullPath: '/backend'
      preLoaderRoute: typeof AuthenticatedBackendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pilot/': {
      id: '/_authenticated/pilot/'
      path: '/'
      fullPath: '/pilot/'
      preLoaderRoute: typeof AuthenticatedPilotIndexRouteImport
      parentRoute: typeof AuthenticatedPilotRoute
    }
    '/_authenticated/interventions/': {
      id: '/_authenticated/interventions/'
      path: '/interventions'
      fullPath: '/interventions/'
      preLoaderRoute: typeof AuthenticatedInterventionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fiches/': {
      id: '/_authenticated/fiches/'
      path: '/fiches'
      fullPath: '/fiches/'
      preLoaderRoute: typeof AuthenticatedFichesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email-open': {
      id: '/api/public/email-open'
      path: '/api/public/email-open'
      fullPath: '/api/public/email-open'
      preLoaderRoute: typeof ApiPublicEmailOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pilot/objectifs': {
      id: '/_authenticated/pilot/objectifs'
      path: '/objectifs'
      fullPath: '/pilot/objectifs'
      preLoaderRoute: typeof AuthenticatedPilotObjectifsRouteImport
      parentRoute: typeof AuthenticatedPilotRoute
    }
    '/_authenticated/pilot/finance': {
      id: '/_authenticated/pilot/finance'
      path: '/finance'
      fullPath: '/pilot/finance'
      preLoaderRoute: typeof AuthenticatedPilotFinanceRouteImport
      parentRoute: typeof AuthenticatedPilotRoute
    }
    '/_authenticated/pilot/clients': {
      id: '/_authenticated/pilot/clients'
      path: '/clients'
      fullPath: '/pilot/clients'
      preLoaderRoute: typeof AuthenticatedPilotClientsRouteImport
      parentRoute: typeof AuthenticatedPilotRoute
    }
    '/_authenticated/pilot/ca': {
      id: '/_authenticated/pilot/ca'
      path: '/ca'
      fullPath: '/pilot/ca'
      preLoaderRoute: typeof AuthenticatedPilotCaRouteImport
      parentRoute: typeof AuthenticatedPilotRoute
    }
    '/_authenticated/interventions/new': {
      id: '/_authenticated/interventions/new'
      path: '/interventions/new'
      fullPath: '/interventions/new'
      preLoaderRoute: typeof AuthenticatedInterventionsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interventions/$interventionId': {
      id: '/_authenticated/interventions/$interventionId'
      path: '/interventions/$interventionId'
      fullPath: '/interventions/$interventionId'
      preLoaderRoute: typeof AuthenticatedInterventionsInterventionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fiches/new': {
      id: '/_authenticated/fiches/new'
      path: '/fiches/new'
      fullPath: '/fiches/new'
      preLoaderRoute: typeof AuthenticatedFichesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fiches/$ficheId': {
      id: '/_authenticated/fiches/$ficheId'
      path: '/fiches/$ficheId'
      fullPath: '/fiches/$ficheId'
      preLoaderRoute: typeof AuthenticatedFichesFicheIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPilotRouteChildren {
  AuthenticatedPilotCaRoute: typeof AuthenticatedPilotCaRoute
  AuthenticatedPilotClientsRoute: typeof AuthenticatedPilotClientsRoute
  AuthenticatedPilotFinanceRoute: typeof AuthenticatedPilotFinanceRoute
  AuthenticatedPilotObjectifsRoute: typeof AuthenticatedPilotObjectifsRoute
  AuthenticatedPilotIndexRoute: typeof AuthenticatedPilotIndexRoute
}

const AuthenticatedPilotRouteChildren: AuthenticatedPilotRouteChildren = {
  AuthenticatedPilotCaRoute: AuthenticatedPilotCaRoute,
  AuthenticatedPilotClientsRoute: AuthenticatedPilotClientsRoute,
  AuthenticatedPilotFinanceRoute: AuthenticatedPilotFinanceRoute,
  AuthenticatedPilotObjectifsRoute: AuthenticatedPilotObjectifsRoute,
  AuthenticatedPilotIndexRoute: AuthenticatedPilotIndexRoute,
}

const AuthenticatedPilotRouteWithChildren =
  AuthenticatedPilotRoute._addFileChildren(AuthenticatedPilotRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBackendRoute: typeof AuthenticatedBackendRoute
  AuthenticatedEmailsRoute: typeof AuthenticatedEmailsRoute
  AuthenticatedModelesRoute: typeof AuthenticatedModelesRoute
  AuthenticatedPersonnalisationRoute: typeof AuthenticatedPersonnalisationRoute
  AuthenticatedPilotRoute: typeof AuthenticatedPilotRouteWithChildren
  AuthenticatedPlanningRoute: typeof AuthenticatedPlanningRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatistiquesRoute: typeof AuthenticatedStatistiquesRoute
  AuthenticatedVersionsRoute: typeof AuthenticatedVersionsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedFichesFicheIdRoute: typeof AuthenticatedFichesFicheIdRoute
  AuthenticatedFichesNewRoute: typeof AuthenticatedFichesNewRoute
  AuthenticatedInterventionsInterventionIdRoute: typeof AuthenticatedInterventionsInterventionIdRoute
  AuthenticatedInterventionsNewRoute: typeof AuthenticatedInterventionsNewRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedFichesIndexRoute: typeof AuthenticatedFichesIndexRoute
  AuthenticatedInterventionsIndexRoute: typeof AuthenticatedInterventionsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBackendRoute: AuthenticatedBackendRoute,
  AuthenticatedEmailsRoute: AuthenticatedEmailsRoute,
  AuthenticatedModelesRoute: AuthenticatedModelesRoute,
  AuthenticatedPersonnalisationRoute: AuthenticatedPersonnalisationRoute,
  AuthenticatedPilotRoute: AuthenticatedPilotRouteWithChildren,
  AuthenticatedPlanningRoute: AuthenticatedPlanningRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatistiquesRoute: AuthenticatedStatistiquesRoute,
  AuthenticatedVersionsRoute: AuthenticatedVersionsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
  AuthenticatedFichesFicheIdRoute: AuthenticatedFichesFicheIdRoute,
  AuthenticatedFichesNewRoute: AuthenticatedFichesNewRoute,
  AuthenticatedInterventionsInterventionIdRoute:
    AuthenticatedInterventionsInterventionIdRoute,
  AuthenticatedInterventionsNewRoute: AuthenticatedInterventionsNewRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedFichesIndexRoute: AuthenticatedFichesIndexRoute,
  AuthenticatedInterventionsIndexRoute: AuthenticatedInterventionsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  PendingRoute: PendingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  PartageTokenRoute: PartageTokenRoute,
  ApiPublicEmailOpenRoute: ApiPublicEmailOpenRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
